#!/usr/bin/env python3
from pathlib import Path
import sys
root=Path(sys.argv[1] if len(sys.argv)>1 else 'vivi')
def r(p):return(root/p).read_text()
def w(p,s):q=root/p;q.parent.mkdir(parents=True,exist_ok=True);q.write_text(s)
def one(s,a,b,n):
 if a not in s:raise SystemExit('patch marker not found: '+n)
 return s.replace(a,b,1)
# brand
p='app/src/main/res/values/app_name.xml';w(p,r(p).replace('<string name="app_name">VIVI</string>','<string name="app_name">Jettmusic</string>'))
# importer
p='app/src/main/AndroidManifest.xml';s=r(p);m='        <activity\n            android:name=".WelcomeActivity"';ins='''        <activity\n            android:name=".jett.JettImportActivity"\n            android:exported="false"\n            android:theme="@style/Theme.vivimusic" />\n\n        <activity\n            android:name=".WelcomeActivity"''';s=s if '.jett.JettImportActivity' in s else one(s,m,ins,'manifest');w(p,s)
# fast start, preserve v6.0.6 resolver/retry
p='app/src/main/kotlin/com/music/vivi/playback/MusicService.kt';s=r(p)
if 'import androidx.media3.exoplayer.DefaultLoadControl' not in s:s=one(s,'import androidx.media3.exoplayer.DefaultRenderersFactory','import androidx.media3.exoplayer.DefaultRenderersFactory\nimport androidx.media3.exoplayer.DefaultLoadControl','load import')
old='''        val player = ExoPlayer.Builder(this)\n            .setMediaSourceFactory(createMediaSourceFactory())''';new='''        val jettFastLoadControl = DefaultLoadControl.Builder()\n            .setBufferDurationsMs(30_000, 120_000, 200, 600)\n            .setPrioritizeTimeOverSizeThresholds(true)\n            .build()\n\n        val player = ExoPlayer.Builder(this)\n            .setMediaSourceFactory(createMediaSourceFactory())\n            .setLoadControl(jettFastLoadControl)'''
if 'jettFastLoadControl' not in s:s=one(s,old,new,'fast load');w(p,s)
# queue hardening
p='app/src/main/kotlin/com/music/vivi/ui/player/Queue.kt';s=r(p);s=s.replace('queueWindows.sumOf { it.mediaItem.metadata!!.duration }','queueWindows.sumOf { it.mediaItem.metadata?.duration ?: 0L }');s=s.replace('''        LaunchedEffect(mutableQueueWindows, currentWindowIndex) {\n            if (currentWindowIndex != -1) {\n                lazyListState.scrollToItem(currentWindowIndex)\n            }\n        }''','''        LaunchedEffect(queueWindows, currentWindowIndex) {\n            if (queueWindows.isNotEmpty() && currentWindowIndex in queueWindows.indices) {\n                val target = (currentWindowIndex + headerItems).coerceAtMost(queueWindows.size)\n                runCatching { lazyListState.scrollToItem(target) }\n            }\n        }''');s=s.replace('''            val safeFrom = (from.index - headerItems).coerceIn(0, mutableQueueWindows.lastIndex)\n            val safeTo = (to.index - headerItems).coerceIn(0, mutableQueueWindows.lastIndex)\n\n            mutableQueueWindows.move(safeFrom, safeTo)''','''            if (mutableQueueWindows.isNotEmpty()) {\n                val safeFrom = (from.index - headerItems).coerceIn(0, mutableQueueWindows.lastIndex)\n                val safeTo = (to.index - headerItems).coerceIn(0, mutableQueueWindows.lastIndex)\n                mutableQueueWindows.move(safeFrom, safeTo)\n            }''');s=s.replace('''                dragInfo?.let { (from, to) ->\n                    val safeFrom = (from - headerItems).coerceIn(0, queueWindows.lastIndex)''','''                dragInfo?.let { (from, to) ->\n                    if (queueWindows.isEmpty()) { dragInfo = null; return@let }\n                    val safeFrom = (from - headerItems).coerceIn(0, queueWindows.lastIndex)''');w(p,s)
# model viewmodel
p='app/src/main/kotlin/com/music/vivi/viewmodels/HomeViewModel.kt';s=r(p)
if 'import com.music.vivi.jett.JettRecommendations' not in s:s=one(s,'import com.music.vivi.models.SimilarRecommendation','import com.music.vivi.models.SimilarRecommendation\nimport com.music.vivi.jett.JettRecommendations','rec import')
if 'val jettRecommendations' not in s:s=one(s,'    val quickPicks = MutableStateFlow<List<Song>?>(null)','    val quickPicks = MutableStateFlow<List<Song>?>(null)\n    val jettRecommendations = MutableStateFlow<List<SongItem>?>(null)','rec state')
marker='''    /**\n     * Phase 2: Fires all network sections concurrently.''';fn='''    private suspend fun loadJettRecommendations() {\n        val engine = JettRecommendations(context)\n        if (engine.seedCount() == 0) { jettRecommendations.value = emptyList(); return }\n        jettRecommendations.value = engine.get(36)\n            .filterExplicit(context.dataStore.get(HideExplicitKey, false))\n            .filterVideoSongs(context.dataStore.get(HideVideoSongsKey, false))\n            .distinctBy { it.id }\n    }\n\n'''
if 'private suspend fun loadJettRecommendations()' not in s:s=one(s,marker,fn+marker,'rec function')
if 'launch(Dispatchers.IO) { loadJettRecommendations() }' not in s:s=one(s,'            launch(Dispatchers.IO) { getDailyDiscover() }','            launch(Dispatchers.IO) { getDailyDiscover() }\n            launch(Dispatchers.IO) { loadJettRecommendations() }','rec launch');w(p,s)
# Home minimal native integration
p='app/src/main/kotlin/com/music/vivi/ui/screens/HomeScreen.kt';s=r(p)
if 'import android.content.Intent' not in s:s=one(s,'package com.music.vivi.ui.screens\n','package com.music.vivi.ui.screens\n\nimport android.content.Intent\n','Intent')
if 'import com.music.vivi.jett.JettImportActivity' not in s:s=one(s,'import com.music.vivi.viewmodels.HomeViewModel','import com.music.vivi.viewmodels.HomeViewModel\nimport com.music.vivi.jett.JettImportActivity','activity import')
if 'JettRecommended' not in s:s=one(s,'    data object QuickPicks : HomeSection("quick_picks", 90)','    data object JettRecommended : HomeSection("jett_recommended", 95)\n    data object QuickPicks : HomeSection("quick_picks", 90)','section')
if 'val jettRecommendations by' not in s:s=one(s,'    val quickPicks by viewModel.quickPicks.collectAsState()','    val quickPicks by viewModel.quickPicks.collectAsState()\n    val jettRecommendations by viewModel.jettRecommendations.collectAsState()','collect')
s=s.replace('        if (!chipActive && speedDialItems.isNotEmpty()) list.add(HomeSection.SpeedDial)','        if (!chipActive && speedDialItems.isNotEmpty()) list.add(HomeSection.SpeedDial)\n        if (!chipActive && jettRecommendations?.isNotEmpty() == true) list.add(HomeSection.JettRecommended)');s=s.replace('                HomeSection.SpeedDial to 100,\n                HomeSection.QuickPicks to 90,','                HomeSection.SpeedDial to 100,\n                HomeSection.JettRecommended to 95,\n                HomeSection.QuickPicks to 90,')
# Ensure context at HomeScreen scope
needle='''    val database = LocalDatabase.current\n    val playerConnection = LocalPlayerConnection.current ?: return\n    val haptic = LocalHapticFeedback.current'''
if needle in s and 'val context = LocalContext.current' not in s[s.index(needle):s.index(needle)+300]:s=s.replace(needle,needle+'\n    val context = LocalContext.current',1)
chips='''                item {\n                    ChipsRow(\n                        chips = homePage?.chips'''
if 'jett_import_taste' not in s and chips in s:s=s.replace(chips,'''                item(key = "jett_import_taste") {\n                    Row(modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 6.dp), horizontalArrangement = Arrangement.End) {\n                        Button(onClick = { context.startActivity(Intent(context, JettImportActivity::class.java)) }) { Text("Importa gusti CSV/TXT") }\n                    }\n                }\n\n'''+chips,1)
branch='''                        HomeSection.QuickPicks -> {'''
if 'jett_recommended_title' not in s and branch in s:s=s.replace(branch,'''                        HomeSection.JettRecommended -> {\n                            jettRecommendations?.takeIf { it.isNotEmpty() }?.let { songs ->\n                                item(key = "jett_recommended_title") { NavigationTitle(title = "Consigliati per te", modifier = Modifier.animateItem(), onPlayAllClick = { playerConnection.playQueue(ListQueue(title = "Consigliati per te", items = songs.distinctBy { it.id }.map { it.toMediaMetadata().toMediaItem() })) }) }\n                                item(key = "jett_recommended_list") { LazyRow(contentPadding = PaddingValues(horizontal = 16.dp), horizontalArrangement = Arrangement.spacedBy(12.dp), modifier = Modifier.fillMaxWidth().animateItem()) { items(songs.distinctBy { it.id }) { song -> Box(modifier = Modifier.width(180.dp)) { ytGridItem(song) } } } }\n                            }\n                        }\n'''+branch,1)
w(p,s)
print('Jettmusic patches applied')
